FROM python:3.11.5-slim-bookworm 
# https://stackoverflow.com/questions/53835198/integrating-python-poetry-with-docker

ARG YOUR_ENV

ENV YOUR_ENV=${YOUR_ENV} \
  PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  # Poetry's configuration:
  POETRY_NO_INTERACTION=1 \
  POETRY_VIRTUALENVS_CREATE=false \
  POETRY_CACHE_DIR='/var/cache/pypoetry' \
  POETRY_HOME='/usr/local' \
  POETRY_VERSION=1.8.1
# ^^^
# Make sure to update it!

RUN apt-get update \
  && apt-get install -y \
  # deps for installing poetry
  curl \
  && rm -rf /var/lib/apt/lists/*

# System deps:
RUN curl -sSL https://install.python-poetry.org | python3 -

# Copy only requirements to cache them in docker layer
WORKDIR /code
COPY poetry.lock pyproject.toml /code/

# Project initialization:
RUN if [ "$YOUR_ENV" = "production" ]; then \
  poetry install --no-interaction --no-ansi --only=main; \
  else \
  poetry install --no-interaction --no-ansi; \
  fi

# Creating folders, and files for a project:
COPY . /code
